server:
  port : 8081

spring:
  application:
    name: mybatis-sample
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sampledb?useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 10

mybatis:
  type-aliases-package: com.example.sample.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: none